[sources.generate]
type = "generator"
format = "syslog"

[transforms.parse]
type = "remap"
inputs = ["generate"]
file = "./parse.vrl"

[sinks.cli_out]
type = "console"
inputs = ["parse"]
target = "stdout"
encoding = { codec = "json" }